initial-pr
Alexander-Prokhorov/aprokhorov-diploma-1 pull request #1
Opened 2022-07-29 16:08 UTC by Alexander-Prokhorov

2022-08-08 20:58 UTC, ASPecherkin requested changes
Тесты проходят, отсавил несколько комментариев о моментах, которые меня смущают

2022-08-08 20:58 UTC, ASPecherkin commented on cmd/gophermart/accrual/accrual.go
> +func (a *AccrualService) RenewOrderData(orderNo string) error {
кажется эта функция нигде не используется

2022-08-08 20:58 UTC, ASPecherkin commented on cmd/gophermart/handlers/orders.go
> +// 9278923470
кажется лишние комментарии

2022-08-08 20:58 UTC, ASPecherkin commented on cmd/gophermart/main.go
> +	go func(ctx context.Context, database storage.Storage) {
смущает эта функция в main - большая и связана напрямую с бизнес задачей, а не инциализацией приложения 

я бы вытащил её как функцию  в пакет orders/cron и уже тут вызывал бы go startOrderCheckProcess

2022-08-17 14:51 UTC, Alexander-Prokhorov commented on cmd/gophermart/accrual/accrual.go
> +func (a *AccrualService) RenewOrderData(orderNo string) error {
Да, оставлял ее, думал будет нужно, но нет.
Удалил

2022-08-17 14:51 UTC, Alexander-Prokhorov commented on cmd/gophermart/handlers/orders.go
> +// 9278923470
Да, записывал примеры номеров для проверки, удалил

2022-08-17 14:52 UTC, Alexander-Prokhorov commented on cmd/gophermart/main.go
> +	go func(ctx context.Context, database storage.Storage) {
Вынес в accrual/cron

2022-08-17 18:53 UTC, ASPecherkin approved these changes
всё хорошо, все замечания исправлены - принимаю работу

2022-08-18 11:39 UTC, merged